name: Deploy

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Allow Repository Changes
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
        
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Create branch
      - name: Create gh-pages branch
        run: git checkout -b gh-pages

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildsPath: webgl

      - name: Prepare Secrets
        run: echo "${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_WORKSPACE/secret.txt
        
      #Mandatory step it appears otherwise pushing the commit will fail
      - name: Configure Git
        run: |
          gh auth login --with-token < $GITHUB_WORKSPACE/secret.txt
          git config user.name "Dr. Deezix"
          git config user.email "admin@koicaverns"
          
      # Push the game to the repo
      - name: Commit Game
        if: ${{ success() }}
        run: |
          git add $GITHUB_WORKSPACE/webgl/*
          git commit -m "Updated game to commit $GITHUB_SHA from main"
          git push origin gh-pages --force
